"""MathBeast — a verified maths engine.

Problems are generated by code, answers are verified by code, and the model
only explains.
"""

__version__ = "0.1.0"

# SymPy is part of the trust boundary, not just a dependency: the engine's
# correctness guarantee is a claim about a specific CAS behaviour. An
# out-of-range SymPy does not raise, it computes differently.
MIN_SYMPY = (1, 12)


def _check_sympy_version() -> None:
    import sympy

    actual = tuple(int(p) for p in sympy.__version__.split(".")[:2])
    if actual < MIN_SYMPY:
        raise RuntimeError(
            f"mathbeast requires sympy>={'.'.join(map(str, MIN_SYMPY))}, "
            f"found {sympy.__version__}. An older CAS computes differently and "
            "the correctness guarantee would silently degrade."
        )


_check_sympy_version()